//
// HealthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class HealthAPI {

    /**
     Health check
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func healthGet(apiResponseQueue: DispatchQueue = SyncStorageClientAPI.apiResponseQueue, completion: @escaping ((_ data: HealthStatusResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return healthGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Health check
     - GET /health
     -  Get the current health status of the service.
     - returns: RequestBuilder<HealthStatusResponse> 
     */
    open class func healthGetWithRequestBuilder() -> RequestBuilder<HealthStatusResponse> {
        let localVariablePath = "/health"
        let localVariableURLString = SyncStorageClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<HealthStatusResponse>.Type = SyncStorageClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}

