//
// TestResultsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TestResultsAPI {

    /**
     Save in-progress test result
     
     - parameter testRunId: (query) Test Run ID 
     - parameter testResultCutApiModel: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func inProgressTestResultPost(testRunId: String, testResultCutApiModel: TestResultCutApiModel, apiResponseQueue: DispatchQueue = SyncStorageClientAPI.apiResponseQueue, completion: @escaping ((_ data: TestResultSaveResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return inProgressTestResultPostWithRequestBuilder(testRunId: testRunId, testResultCutApiModel: testResultCutApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Save in-progress test result
     - POST /in_progress_test_result
     -  Save a test result with InProgress status.
     - parameter testRunId: (query) Test Run ID 
     - parameter testResultCutApiModel: (body)  
     - returns: RequestBuilder<TestResultSaveResponse> 
     */
    open class func inProgressTestResultPostWithRequestBuilder(testRunId: String, testResultCutApiModel: TestResultCutApiModel) -> RequestBuilder<TestResultSaveResponse> {
        let localVariablePath = "/in_progress_test_result"
        let localVariableURLString = SyncStorageClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: testResultCutApiModel)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "testRunId": (wrappedValue: testRunId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TestResultSaveResponse>.Type = SyncStorageClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}

