//
// WorkersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class WorkersAPI {

    /**
     Register a new worker
     
     - parameter registerRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func registerPost(registerRequest: RegisterRequest, apiResponseQueue: DispatchQueue = SyncStorageClientAPI.apiResponseQueue, completion: @escaping ((_ data: RegisterResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return registerPostWithRequestBuilder(registerRequest: registerRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Register a new worker
     - POST /register
     -  Register a new worker with the sync storage service.
     - parameter registerRequest: (body)  
     - returns: RequestBuilder<RegisterResponse> 
     */
    open class func registerPostWithRequestBuilder(registerRequest: RegisterRequest) -> RequestBuilder<RegisterResponse> {
        let localVariablePath = "/register"
        let localVariableURLString = SyncStorageClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RegisterResponse>.Type = SyncStorageClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Set worker status
     
     - parameter setWorkerStatusRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func setWorkerStatusPost(setWorkerStatusRequest: SetWorkerStatusRequest, apiResponseQueue: DispatchQueue = SyncStorageClientAPI.apiResponseQueue, completion: @escaping ((_ data: SetWorkerStatusResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return setWorkerStatusPostWithRequestBuilder(setWorkerStatusRequest: setWorkerStatusRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Set worker status
     - POST /set_worker_status
     -  Set the status of a worker by its PID.
     - parameter setWorkerStatusRequest: (body)  
     - returns: RequestBuilder<SetWorkerStatusResponse> 
     */
    open class func setWorkerStatusPostWithRequestBuilder(setWorkerStatusRequest: SetWorkerStatusRequest) -> RequestBuilder<SetWorkerStatusResponse> {
        let localVariablePath = "/set_worker_status"
        let localVariableURLString = SyncStorageClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setWorkerStatusRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SetWorkerStatusResponse>.Type = SyncStorageClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}

