//
// HealthStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HealthStatusResponse: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var lastUpdate: Date?

    public init(status: String? = nil, lastUpdate: Date? = nil) {
        self.status = status
        self.lastUpdate = lastUpdate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case lastUpdate = "last_update"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(lastUpdate, forKey: .lastUpdate)
    }
}

