//
// SetWorkerStatusRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetWorkerStatusRequest: Codable, JSONEncodable, Hashable {

    public var pid: String?
    public var status: String?
    public var testRunId: String?

    public init(pid: String? = nil, status: String? = nil, testRunId: String? = nil) {
        self.pid = pid
        self.status = status
        self.testRunId = testRunId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pid
        case status
        case testRunId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pid, forKey: .pid)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(testRunId, forKey: .testRunId)
    }
}

