//
// AttachmentsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AttachmentsAPI {

    /**

     - parameter files: (form)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAttachmentsBulkPost(files: [URL]? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: [AttachmentModel]?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAttachmentsBulkPostWithRequestBuilder(files: files).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /adapters/attachments/bulk
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter files: (form)  (optional)
     - returns: RequestBuilder<[AttachmentModel]> 
     */
    open class func adaptersAttachmentsBulkPostWithRequestBuilder(files: [URL]? = nil) -> RequestBuilder<[AttachmentModel]> {
        let localVariablePath = "/adapters/attachments/bulk"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "files": files?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AttachmentModel]>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Download attachment file
     
     - parameter id: (path)  
     - parameter width: (query) Width of the result image (optional)
     - parameter height: (query) Height of the result image (optional)
     - parameter resizeType: (query) Type of resizing to apply to the result image (optional)
     - parameter backgroundColor: (query) Color of the background if the &#x60;resizeType&#x60; is &#x60;AddBackgroundStripes&#x60; (optional)
     - parameter preview: (query) If image must be converted to a preview (lower quality, no animation) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAttachmentsIdGet(id: UUID, width: Int? = nil, height: Int? = nil, resizeType: ImageResizeType? = nil, backgroundColor: String? = nil, preview: Bool? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAttachmentsIdGetWithRequestBuilder(id: id, width: width, height: height, resizeType: resizeType, backgroundColor: backgroundColor, preview: preview).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Download attachment file
     - GET /adapters/attachments/{id}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - parameter width: (query) Width of the result image (optional)
     - parameter height: (query) Height of the result image (optional)
     - parameter resizeType: (query) Type of resizing to apply to the result image (optional)
     - parameter backgroundColor: (query) Color of the background if the &#x60;resizeType&#x60; is &#x60;AddBackgroundStripes&#x60; (optional)
     - parameter preview: (query) If image must be converted to a preview (lower quality, no animation) (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersAttachmentsIdGetWithRequestBuilder(id: UUID, width: Int? = nil, height: Int? = nil, resizeType: ImageResizeType? = nil, backgroundColor: String? = nil, preview: Bool? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/adapters/attachments/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "width": (wrappedValue: width?.encodeToJSON(), isExplode: true),
            "height": (wrappedValue: height?.encodeToJSON(), isExplode: true),
            "resizeType": (wrappedValue: resizeType?.encodeToJSON(), isExplode: true),
            "backgroundColor": (wrappedValue: backgroundColor?.encodeToJSON(), isExplode: true),
            "preview": (wrappedValue: preview?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upload new attachment file
     
     - parameter file: (form)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAttachmentsPost(file: URL? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: AttachmentModel?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAttachmentsPostWithRequestBuilder(file: file).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Upload new attachment file
     - POST /adapters/attachments
     - File size is restricted to 1 GB (1 073 741 824 bytes)
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter file: (form)  (optional)
     - returns: RequestBuilder<AttachmentModel> 
     */
    open class func adaptersAttachmentsPostWithRequestBuilder(file: URL? = nil) -> RequestBuilder<AttachmentModel> {
        let localVariablePath = "/adapters/attachments"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AttachmentModel>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
