//
// AutoTestsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AutoTestsAPI {

    /**
     Create multiple autotests
     
     - parameter autoTestCreateApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsBulkPost(autoTestCreateApiModel: [AutoTestCreateApiModel]? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: [AutoTestApiResult]?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsBulkPostWithRequestBuilder(autoTestCreateApiModel: autoTestCreateApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create multiple autotests
     - POST /adapters/autoTests/bulk
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter autoTestCreateApiModel: (body)  (optional)
     - returns: RequestBuilder<[AutoTestApiResult]> 
     */
    open class func adaptersAutoTestsBulkPostWithRequestBuilder(autoTestCreateApiModel: [AutoTestCreateApiModel]? = nil) -> RequestBuilder<[AutoTestApiResult]> {
        let localVariablePath = "/adapters/autoTests/bulk"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: autoTestCreateApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AutoTestApiResult]>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update multiple autotests
     
     - parameter autoTestUpdateApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsBulkPut(autoTestUpdateApiModel: [AutoTestUpdateApiModel]? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsBulkPutWithRequestBuilder(autoTestUpdateApiModel: autoTestUpdateApiModel).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update multiple autotests
     - PUT /adapters/autoTests/bulk
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter autoTestUpdateApiModel: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersAutoTestsBulkPutWithRequestBuilder(autoTestUpdateApiModel: [AutoTestUpdateApiModel]? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/adapters/autoTests/bulk"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: autoTestUpdateApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter projectId: (query) Project internal ID (optional)
     - parameter externalId: (query) Autotest external ID (optional)
     - parameter globalId: (query) Autotest global ID (optional)
     - parameter namespace: (query) Namespace in which autotest is located (optional)
     - parameter isNamespaceNull: (query) OBSOLETE: Use &#x60;includeEmptyNamespaces&#x60; instead (optional)
     - parameter includeEmptyNamespaces: (query) If result must contain autotests without namespace (optional)
     - parameter className: (query) Name of class in which autotest is located (optional)
     - parameter isClassnameNull: (query) OBSOLETE: Use &#x60;includeEmptyClassNames&#x60; instead (optional)
     - parameter includeEmptyClassNames: (query) If result must contain autotests without class (optional)
     - parameter isDeleted: (query) OBSOLETE: Use &#x60;deleted&#x60; instead (optional)
     - parameter deleted: (query) Is autotest deleted (optional)
     - parameter labels: (query) Include only autotests with provided labels (optional)
     - parameter stabilityMinimal: (query) OBSOLETE: Use &#x60;minStability&#x60; instead (optional)
     - parameter minStability: (query) Minimum stability value of autotest (optional)
     - parameter stabilityMaximal: (query) OBSOLETE: Use &#x60;maxStability&#x60; instead (optional)
     - parameter maxStability: (query) Maximum stability value of autotest (optional)
     - parameter isFlaky: (query) OBSOLETE: Use &#x60;flaky&#x60; instead (optional)
     - parameter flaky: (query) Is autotest marked as \&quot;Flaky\&quot; (optional)
     - parameter includeSteps: (query) If result must also include autotest steps (optional)
     - parameter includeLabels: (query) If result must also include autotest labels (optional)
     - parameter externalKey: (query) External key of autotest (optional)
     - parameter skip: (query) Amount of items to be skipped (offset) (optional)
     - parameter take: (query) Amount of items to be taken (limit) (optional)
     - parameter orderBy: (query) SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     - parameter searchField: (query) Property name for searching (optional)
     - parameter searchValue: (query) Value for searching (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    @discardableResult
    open class func adaptersAutoTestsGet(projectId: UUID? = nil, externalId: String? = nil, globalId: Int64? = nil, namespace: String? = nil, isNamespaceNull: Bool? = nil, includeEmptyNamespaces: Bool? = nil, className: String? = nil, isClassnameNull: Bool? = nil, includeEmptyClassNames: Bool? = nil, isDeleted: Bool? = nil, deleted: Bool? = nil, labels: [String]? = nil, stabilityMinimal: Int? = nil, minStability: Int? = nil, stabilityMaximal: Int? = nil, maxStability: Int? = nil, isFlaky: Bool? = nil, flaky: Bool? = nil, includeSteps: Bool? = nil, includeLabels: Bool? = nil, externalKey: String? = nil, skip: Int? = nil, take: Int? = nil, orderBy: String? = nil, searchField: String? = nil, searchValue: String? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: [AutoTestModel]?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsGetWithRequestBuilder(projectId: projectId, externalId: externalId, globalId: globalId, namespace: namespace, isNamespaceNull: isNamespaceNull, includeEmptyNamespaces: includeEmptyNamespaces, className: className, isClassnameNull: isClassnameNull, includeEmptyClassNames: includeEmptyClassNames, isDeleted: isDeleted, deleted: deleted, labels: labels, stabilityMinimal: stabilityMinimal, minStability: minStability, stabilityMaximal: stabilityMaximal, maxStability: maxStability, isFlaky: isFlaky, flaky: flaky, includeSteps: includeSteps, includeLabels: includeLabels, externalKey: externalKey, skip: skip, take: take, orderBy: orderBy, searchField: searchField, searchValue: searchValue).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /adapters/autoTests
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - responseHeaders: [Pagination-Skip(Int), Pagination-Take(Int), Pagination-Pages(Int), Pagination-Total-Items(Int)]
     - parameter projectId: (query) Project internal ID (optional)
     - parameter externalId: (query) Autotest external ID (optional)
     - parameter globalId: (query) Autotest global ID (optional)
     - parameter namespace: (query) Namespace in which autotest is located (optional)
     - parameter isNamespaceNull: (query) OBSOLETE: Use &#x60;includeEmptyNamespaces&#x60; instead (optional)
     - parameter includeEmptyNamespaces: (query) If result must contain autotests without namespace (optional)
     - parameter className: (query) Name of class in which autotest is located (optional)
     - parameter isClassnameNull: (query) OBSOLETE: Use &#x60;includeEmptyClassNames&#x60; instead (optional)
     - parameter includeEmptyClassNames: (query) If result must contain autotests without class (optional)
     - parameter isDeleted: (query) OBSOLETE: Use &#x60;deleted&#x60; instead (optional)
     - parameter deleted: (query) Is autotest deleted (optional)
     - parameter labels: (query) Include only autotests with provided labels (optional)
     - parameter stabilityMinimal: (query) OBSOLETE: Use &#x60;minStability&#x60; instead (optional)
     - parameter minStability: (query) Minimum stability value of autotest (optional)
     - parameter stabilityMaximal: (query) OBSOLETE: Use &#x60;maxStability&#x60; instead (optional)
     - parameter maxStability: (query) Maximum stability value of autotest (optional)
     - parameter isFlaky: (query) OBSOLETE: Use &#x60;flaky&#x60; instead (optional)
     - parameter flaky: (query) Is autotest marked as \&quot;Flaky\&quot; (optional)
     - parameter includeSteps: (query) If result must also include autotest steps (optional)
     - parameter includeLabels: (query) If result must also include autotest labels (optional)
     - parameter externalKey: (query) External key of autotest (optional)
     - parameter skip: (query) Amount of items to be skipped (offset) (optional)
     - parameter take: (query) Amount of items to be taken (limit) (optional)
     - parameter orderBy: (query) SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     - parameter searchField: (query) Property name for searching (optional)
     - parameter searchValue: (query) Value for searching (optional)
     - returns: RequestBuilder<[AutoTestModel]> 
     */
    @available(*, deprecated, message: "This operation is deprecated.")
    open class func adaptersAutoTestsGetWithRequestBuilder(projectId: UUID? = nil, externalId: String? = nil, globalId: Int64? = nil, namespace: String? = nil, isNamespaceNull: Bool? = nil, includeEmptyNamespaces: Bool? = nil, className: String? = nil, isClassnameNull: Bool? = nil, includeEmptyClassNames: Bool? = nil, isDeleted: Bool? = nil, deleted: Bool? = nil, labels: [String]? = nil, stabilityMinimal: Int? = nil, minStability: Int? = nil, stabilityMaximal: Int? = nil, maxStability: Int? = nil, isFlaky: Bool? = nil, flaky: Bool? = nil, includeSteps: Bool? = nil, includeLabels: Bool? = nil, externalKey: String? = nil, skip: Int? = nil, take: Int? = nil, orderBy: String? = nil, searchField: String? = nil, searchValue: String? = nil) -> RequestBuilder<[AutoTestModel]> {
        let localVariablePath = "/adapters/autoTests"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "projectId": (wrappedValue: projectId?.encodeToJSON(), isExplode: true),
            "externalId": (wrappedValue: externalId?.encodeToJSON(), isExplode: true),
            "globalId": (wrappedValue: globalId?.encodeToJSON(), isExplode: true),
            "namespace": (wrappedValue: namespace?.encodeToJSON(), isExplode: true),
            "isNamespaceNull": (wrappedValue: isNamespaceNull?.encodeToJSON(), isExplode: true),
            "includeEmptyNamespaces": (wrappedValue: includeEmptyNamespaces?.encodeToJSON(), isExplode: true),
            "className": (wrappedValue: className?.encodeToJSON(), isExplode: true),
            "isClassnameNull": (wrappedValue: isClassnameNull?.encodeToJSON(), isExplode: true),
            "includeEmptyClassNames": (wrappedValue: includeEmptyClassNames?.encodeToJSON(), isExplode: true),
            "isDeleted": (wrappedValue: isDeleted?.encodeToJSON(), isExplode: true),
            "deleted": (wrappedValue: deleted?.encodeToJSON(), isExplode: true),
            "labels": (wrappedValue: labels?.encodeToJSON(), isExplode: true),
            "stabilityMinimal": (wrappedValue: stabilityMinimal?.encodeToJSON(), isExplode: true),
            "minStability": (wrappedValue: minStability?.encodeToJSON(), isExplode: true),
            "stabilityMaximal": (wrappedValue: stabilityMaximal?.encodeToJSON(), isExplode: true),
            "maxStability": (wrappedValue: maxStability?.encodeToJSON(), isExplode: true),
            "isFlaky": (wrappedValue: isFlaky?.encodeToJSON(), isExplode: true),
            "flaky": (wrappedValue: flaky?.encodeToJSON(), isExplode: true),
            "includeSteps": (wrappedValue: includeSteps?.encodeToJSON(), isExplode: true),
            "includeLabels": (wrappedValue: includeLabels?.encodeToJSON(), isExplode: true),
            "externalKey": (wrappedValue: externalKey?.encodeToJSON(), isExplode: true),
            "Skip": (wrappedValue: skip?.encodeToJSON(), isExplode: true),
            "Take": (wrappedValue: take?.encodeToJSON(), isExplode: true),
            "OrderBy": (wrappedValue: orderBy?.encodeToJSON(), isExplode: true),
            "SearchField": (wrappedValue: searchField?.encodeToJSON(), isExplode: true),
            "SearchValue": (wrappedValue: searchValue?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AutoTestModel]>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get autotest by internal or global ID
     
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsIdGet(id: String, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: AutoTestApiResult?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get autotest by internal or global ID
     - GET /adapters/autoTests/{id}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - returns: RequestBuilder<AutoTestApiResult> 
     */
    open class func adaptersAutoTestsIdGetWithRequestBuilder(id: String) -> RequestBuilder<AutoTestApiResult> {
        var localVariablePath = "/adapters/autoTests/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AutoTestApiResult>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Patch auto test
     
     - parameter id: (path)  
     - parameter operation: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsIdPatch(id: UUID, operation: [Operation]? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsIdPatchWithRequestBuilder(id: id, operation: operation).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Patch auto test
     - PATCH /adapters/autoTests/{id}
     - See <a href=\"https://www.rfc-editor.org/rfc/rfc6902\" target=\"_blank\">RFC 6902: JavaScript Object Notation (JSON) Patch</a> for details
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - parameter operation: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersAutoTestsIdPatchWithRequestBuilder(id: UUID, operation: [Operation]? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/adapters/autoTests/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: operation)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Unlink autotest from work item
     
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - parameter workItemId: (query) Internal (UUID) or global (integer) identifier (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsIdWorkItemsDelete(id: String, workItemId: String? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsIdWorkItemsDeleteWithRequestBuilder(id: id, workItemId: workItemId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Unlink autotest from work item
     - DELETE /adapters/autoTests/{id}/work-items
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - parameter workItemId: (query) Internal (UUID) or global (integer) identifier (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersAutoTestsIdWorkItemsDeleteWithRequestBuilder(id: String, workItemId: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/adapters/autoTests/{id}/work-items"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "workItemId": (wrappedValue: workItemId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get work items linked to autotest
     
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - parameter isDeleted: (query)  (optional)
     - parameter isWorkItemDeleted: (query)  (optional, default to false)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsIdWorkItemsGet(id: String, isDeleted: Bool? = nil, isWorkItemDeleted: Bool? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: [AutoTestWorkItemIdentifierApiResult]?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsIdWorkItemsGetWithRequestBuilder(id: id, isDeleted: isDeleted, isWorkItemDeleted: isWorkItemDeleted).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get work items linked to autotest
     - GET /adapters/autoTests/{id}/work-items
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - parameter isDeleted: (query)  (optional)
     - parameter isWorkItemDeleted: (query)  (optional, default to false)
     - returns: RequestBuilder<[AutoTestWorkItemIdentifierApiResult]> 
     */
    open class func adaptersAutoTestsIdWorkItemsGetWithRequestBuilder(id: String, isDeleted: Bool? = nil, isWorkItemDeleted: Bool? = nil) -> RequestBuilder<[AutoTestWorkItemIdentifierApiResult]> {
        var localVariablePath = "/adapters/autoTests/{id}/work-items"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "isDeleted": (wrappedValue: isDeleted?.encodeToJSON(), isExplode: true),
            "isWorkItemDeleted": (wrappedValue: isWorkItemDeleted?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AutoTestWorkItemIdentifierApiResult]>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Link autotest with work items
     
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - parameter workItemIdApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsIdWorkItemsPost(id: String, workItemIdApiModel: WorkItemIdApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsIdWorkItemsPostWithRequestBuilder(id: id, workItemIdApiModel: workItemIdApiModel).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Link autotest with work items
     - POST /adapters/autoTests/{id}/work-items
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path) Internal (UUID) or global (integer) identifier 
     - parameter workItemIdApiModel: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersAutoTestsIdWorkItemsPostWithRequestBuilder(id: String, workItemIdApiModel: WorkItemIdApiModel? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/adapters/autoTests/{id}/work-items"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: workItemIdApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create autotest
     
     - parameter autoTestCreateApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsPost(autoTestCreateApiModel: AutoTestCreateApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: AutoTestApiResult?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsPostWithRequestBuilder(autoTestCreateApiModel: autoTestCreateApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create autotest
     - POST /adapters/autoTests
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter autoTestCreateApiModel: (body)  (optional)
     - returns: RequestBuilder<AutoTestApiResult> 
     */
    open class func adaptersAutoTestsPostWithRequestBuilder(autoTestCreateApiModel: AutoTestCreateApiModel? = nil) -> RequestBuilder<AutoTestApiResult> {
        let localVariablePath = "/adapters/autoTests"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: autoTestCreateApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AutoTestApiResult>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update autotest
     
     - parameter autoTestUpdateApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsPut(autoTestUpdateApiModel: AutoTestUpdateApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsPutWithRequestBuilder(autoTestUpdateApiModel: autoTestUpdateApiModel).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update autotest
     - PUT /adapters/autoTests
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter autoTestUpdateApiModel: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersAutoTestsPutWithRequestBuilder(autoTestUpdateApiModel: AutoTestUpdateApiModel? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/adapters/autoTests"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: autoTestUpdateApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search for autotests
     
     - parameter skip: (query) Amount of items to be skipped (offset) (optional)
     - parameter take: (query) Amount of items to be taken (limit) (optional)
     - parameter orderBy: (query) SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     - parameter searchField: (query) Property name for searching (optional)
     - parameter searchValue: (query) Value for searching (optional)
     - parameter autoTestSearchApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersAutoTestsSearchPost(skip: Int? = nil, take: Int? = nil, orderBy: String? = nil, searchField: String? = nil, searchValue: String? = nil, autoTestSearchApiModel: AutoTestSearchApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: [AutoTestApiResult]?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersAutoTestsSearchPostWithRequestBuilder(skip: skip, take: take, orderBy: orderBy, searchField: searchField, searchValue: searchValue, autoTestSearchApiModel: autoTestSearchApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search for autotests
     - POST /adapters/autoTests/search
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - responseHeaders: [Pagination-Skip(Int), Pagination-Take(Int), Pagination-Pages(Int), Pagination-Total-Items(Int)]
     - parameter skip: (query) Amount of items to be skipped (offset) (optional)
     - parameter take: (query) Amount of items to be taken (limit) (optional)
     - parameter orderBy: (query) SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     - parameter searchField: (query) Property name for searching (optional)
     - parameter searchValue: (query) Value for searching (optional)
     - parameter autoTestSearchApiModel: (body)  (optional)
     - returns: RequestBuilder<[AutoTestApiResult]> 
     */
    open class func adaptersAutoTestsSearchPostWithRequestBuilder(skip: Int? = nil, take: Int? = nil, orderBy: String? = nil, searchField: String? = nil, searchValue: String? = nil, autoTestSearchApiModel: AutoTestSearchApiModel? = nil) -> RequestBuilder<[AutoTestApiResult]> {
        let localVariablePath = "/adapters/autoTests/search"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: autoTestSearchApiModel)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Skip": (wrappedValue: skip?.encodeToJSON(), isExplode: true),
            "Take": (wrappedValue: take?.encodeToJSON(), isExplode: true),
            "OrderBy": (wrappedValue: orderBy?.encodeToJSON(), isExplode: true),
            "SearchField": (wrappedValue: searchField?.encodeToJSON(), isExplode: true),
            "SearchValue": (wrappedValue: searchValue?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AutoTestApiResult]>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
