//
// ParametersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ParametersAPI {

    /**
     Get parameter by ID
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersParametersIdGet(id: UUID, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: ParameterApiResult?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersParametersIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get parameter by ID
     - GET /adapters/parameters/{id}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey backoffice 
       - name: Identity.Application
     - parameter id: (path)  
     - returns: RequestBuilder<ParameterApiResult> 
     */
    open class func adaptersParametersIdGetWithRequestBuilder(id: UUID) -> RequestBuilder<ParameterApiResult> {
        var localVariablePath = "/adapters/parameters/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ParameterApiResult>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create parameter
     
     - parameter createParameterApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersParametersPost(createParameterApiModel: CreateParameterApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: ParameterApiResult?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersParametersPostWithRequestBuilder(createParameterApiModel: createParameterApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create parameter
     - POST /adapters/parameters
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey backoffice 
       - name: Identity.Application
     - parameter createParameterApiModel: (body)  (optional)
     - returns: RequestBuilder<ParameterApiResult> 
     */
    open class func adaptersParametersPostWithRequestBuilder(createParameterApiModel: CreateParameterApiModel? = nil) -> RequestBuilder<ParameterApiResult> {
        let localVariablePath = "/adapters/parameters"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createParameterApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ParameterApiResult>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Search for parameters
     
     - parameter skip: (query) Amount of items to be skipped (offset) (optional)
     - parameter take: (query) Amount of items to be taken (limit) (optional)
     - parameter orderBy: (query) SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     - parameter searchField: (query) Property name for searching (optional)
     - parameter searchValue: (query) Value for searching (optional)
     - parameter parametersFilterApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersParametersSearchPost(skip: Int? = nil, take: Int? = nil, orderBy: String? = nil, searchField: String? = nil, searchValue: String? = nil, parametersFilterApiModel: ParametersFilterApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: [ParameterApiResult]?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersParametersSearchPostWithRequestBuilder(skip: skip, take: take, orderBy: orderBy, searchField: searchField, searchValue: searchValue, parametersFilterApiModel: parametersFilterApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Search for parameters
     - POST /adapters/parameters/search
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey backoffice 
       - name: Identity.Application
     - responseHeaders: [Pagination-Skip(Int), Pagination-Take(Int), Pagination-Pages(Int), Pagination-Total-Items(Int)]
     - parameter skip: (query) Amount of items to be skipped (offset) (optional)
     - parameter take: (query) Amount of items to be taken (limit) (optional)
     - parameter orderBy: (query) SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     - parameter searchField: (query) Property name for searching (optional)
     - parameter searchValue: (query) Value for searching (optional)
     - parameter parametersFilterApiModel: (body)  (optional)
     - returns: RequestBuilder<[ParameterApiResult]> 
     */
    open class func adaptersParametersSearchPostWithRequestBuilder(skip: Int? = nil, take: Int? = nil, orderBy: String? = nil, searchField: String? = nil, searchValue: String? = nil, parametersFilterApiModel: ParametersFilterApiModel? = nil) -> RequestBuilder<[ParameterApiResult]> {
        let localVariablePath = "/adapters/parameters/search"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: parametersFilterApiModel)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Skip": (wrappedValue: skip?.encodeToJSON(), isExplode: true),
            "Take": (wrappedValue: take?.encodeToJSON(), isExplode: true),
            "OrderBy": (wrappedValue: orderBy?.encodeToJSON(), isExplode: true),
            "SearchField": (wrappedValue: searchField?.encodeToJSON(), isExplode: true),
            "SearchValue": (wrappedValue: searchValue?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ParameterApiResult]>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
