//
// TestRunsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TestRunsAPI {

    /**
     Complete TestRun
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsIdCompletePost(id: UUID, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsIdCompletePostWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Complete TestRun
     - POST /adapters/testRuns/{id}/complete
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersTestRunsIdCompletePostWithRequestBuilder(id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/adapters/testRuns/{id}/complete"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get TestRun by Id
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsIdGet(id: UUID, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: TestRunApiResult?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsIdGetWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get TestRun by Id
     - GET /adapters/testRuns/{id}
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - returns: RequestBuilder<TestRunApiResult> 
     */
    open class func adaptersTestRunsIdGetWithRequestBuilder(id: UUID) -> RequestBuilder<TestRunApiResult> {
        var localVariablePath = "/adapters/testRuns/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TestRunApiResult>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Manual autotests rerun in test run
     
     - parameter id: (path)  
     - parameter manualRerunSelectTestResultsApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsIdRerunsPost(id: UUID, manualRerunSelectTestResultsApiModel: ManualRerunSelectTestResultsApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: ManualRerunApiResult?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsIdRerunsPostWithRequestBuilder(id: id, manualRerunSelectTestResultsApiModel: manualRerunSelectTestResultsApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Manual autotests rerun in test run
     - POST /adapters/testRuns/{id}/reruns
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - parameter manualRerunSelectTestResultsApiModel: (body)  (optional)
     - returns: RequestBuilder<ManualRerunApiResult> 
     */
    open class func adaptersTestRunsIdRerunsPostWithRequestBuilder(id: UUID, manualRerunSelectTestResultsApiModel: ManualRerunSelectTestResultsApiModel? = nil) -> RequestBuilder<ManualRerunApiResult> {
        var localVariablePath = "/adapters/testRuns/{id}/reruns"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: manualRerunSelectTestResultsApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ManualRerunApiResult>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Start TestRun
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsIdStartPost(id: UUID, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsIdStartPostWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Start TestRun
     - POST /adapters/testRuns/{id}/start
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersTestRunsIdStartPostWithRequestBuilder(id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/adapters/testRuns/{id}/start"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Stop TestRun
     
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsIdStopPost(id: UUID, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsIdStopPostWithRequestBuilder(id: id).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Stop TestRun
     - POST /adapters/testRuns/{id}/stop
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersTestRunsIdStopPostWithRequestBuilder(id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/adapters/testRuns/{id}/stop"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Send test results to the test runs in the system
     
     - parameter id: (path)  
     - parameter autoTestResultsForTestRunModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsIdTestResultsPost(id: UUID, autoTestResultsForTestRunModel: [AutoTestResultsForTestRunModel]? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: [UUID]?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsIdTestResultsPostWithRequestBuilder(id: id, autoTestResultsForTestRunModel: autoTestResultsForTestRunModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Send test results to the test runs in the system
     - POST /adapters/testRuns/{id}/test-results
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter id: (path)  
     - parameter autoTestResultsForTestRunModel: (body)  (optional)
     - returns: RequestBuilder<[UUID]> 
     */
    open class func adaptersTestRunsIdTestResultsPostWithRequestBuilder(id: UUID, autoTestResultsForTestRunModel: [AutoTestResultsForTestRunModel]? = nil) -> RequestBuilder<[UUID]> {
        var localVariablePath = "/adapters/testRuns/{id}/test-results"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: autoTestResultsForTestRunModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UUID]>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create empty TestRun
     
     - parameter createEmptyTestRunApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsPost(createEmptyTestRunApiModel: CreateEmptyTestRunApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: TestRunApiResult?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsPostWithRequestBuilder(createEmptyTestRunApiModel: createEmptyTestRunApiModel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create empty TestRun
     - POST /adapters/testRuns
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter createEmptyTestRunApiModel: (body)  (optional)
     - returns: RequestBuilder<TestRunApiResult> 
     */
    open class func adaptersTestRunsPostWithRequestBuilder(createEmptyTestRunApiModel: CreateEmptyTestRunApiModel? = nil) -> RequestBuilder<TestRunApiResult> {
        let localVariablePath = "/adapters/testRuns"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createEmptyTestRunApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TestRunApiResult>.Type = AdaptersApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update empty TestRun
     
     - parameter updateEmptyTestRunApiModel: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func adaptersTestRunsPut(updateEmptyTestRunApiModel: UpdateEmptyTestRunApiModel? = nil, apiResponseQueue: DispatchQueue = AdaptersApiAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return adaptersTestRunsPutWithRequestBuilder(updateEmptyTestRunApiModel: updateEmptyTestRunApiModel).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update empty TestRun
     - PUT /adapters/testRuns
     - API Key:
       - type: apiKey Authorization (HEADER)
       - name: PrivateToken
     - API Key:
       - type: apiKey session 
       - name: Cookies
     - parameter updateEmptyTestRunApiModel: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func adaptersTestRunsPutWithRequestBuilder(updateEmptyTestRunApiModel: UpdateEmptyTestRunApiModel? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/adapters/testRuns"
        let localVariableURLString = AdaptersApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateEmptyTestRunApiModel)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = AdaptersApiAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
