//
// RegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
public struct RegisterRequest: Codable, JSONEncodable, Hashable {

    public var pid: String?
    public var testRunId: String?
    public var baseUrl: String?
    public var privateToken: String?

    public init(pid: String? = nil, testRunId: String? = nil, baseUrl: String? = nil, privateToken: String? = nil) {
        self.pid = pid
        self.testRunId = testRunId
        self.baseUrl = baseUrl
        self.privateToken = privateToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pid
        case testRunId
        case baseUrl
        case privateToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pid, forKey: .pid)
        try container.encodeIfPresent(testRunId, forKey: .testRunId)
        try container.encodeIfPresent(baseUrl, forKey: .baseUrl)
        try container.encodeIfPresent(privateToken, forKey: .privateToken)
    }
}

