//
// RegisterResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterResponse: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var message: String?
    public var pid: String?
    public var testRunId: String?
    public var isMaster: Bool?

    public init(status: String? = nil, message: String? = nil, pid: String? = nil, testRunId: String? = nil, isMaster: Bool? = nil) {
        self.status = status
        self.message = message
        self.pid = pid
        self.testRunId = testRunId
        self.isMaster = isMaster
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case message
        case pid
        case testRunId
        case isMaster = "is_master"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(pid, forKey: .pid)
        try container.encodeIfPresent(testRunId, forKey: .testRunId)
        try container.encodeIfPresent(isMaster, forKey: .isMaster)
    }
}

