//
// TestResultCutApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
public struct TestResultCutApiModel: Codable, JSONEncodable, Hashable {

    public var projectId: String?
    public var autoTestExternalId: String?
    public var statusCode: String?
    public var statusType: String?
    public var startedOn: Date?

    public init(projectId: String? = nil, autoTestExternalId: String? = nil, statusCode: String? = nil, statusType: String? = nil, startedOn: Date? = nil) {
        self.projectId = projectId
        self.autoTestExternalId = autoTestExternalId
        self.statusCode = statusCode
        self.statusType = statusType
        self.startedOn = startedOn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId
        case autoTestExternalId
        case statusCode
        case statusType
        case startedOn
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectId, forKey: .projectId)
        try container.encodeIfPresent(autoTestExternalId, forKey: .autoTestExternalId)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(statusType, forKey: .statusType)
        try container.encodeIfPresent(startedOn, forKey: .startedOn)
    }
}

