//
// AttachmentApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AttachmentApiResult: Codable, JSONEncodable, Hashable {

    /** Unique ID of the attachment */
    public var id: UUID
    /** Unique ID of the attachment file */
    public var fileId: String
    /** MIME type of the attachment */
    public var type: String
    /** Size in bytes of the attachment file */
    public var size: Float
    /** Name of the attachment file */
    public var name: String

    public init(id: UUID, fileId: String, type: String, size: Float, name: String) {
        self.id = id
        self.fileId = fileId
        self.type = type
        self.size = size
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case fileId
        case type
        case size
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(fileId, forKey: .fileId)
        try container.encode(type, forKey: .type)
        try container.encode(size, forKey: .size)
        try container.encode(name, forKey: .name)
    }
}

