//
// AutoTest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTest: Codable, JSONEncodable, Hashable {

    static let externalIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** External ID of the autotest */
    public var externalId: String
    /** Collection of the autotest links */
    public var links: [LinkApiResult]?
    /** Unique ID of the autotest project */
    public var projectId: UUID
    /** Name of the autotest */
    public var name: String
    /** Name of the autotest namespace */
    public var namespace: String?
    /** Name of the autotest class */
    public var classname: String?
    /** Collection of the autotest steps */
    public var steps: [AutoTestStep]?
    /** Collection of the autotest setup steps */
    public var setup: [AutoTestStep]?
    /** Collection of the autotest teardown steps */
    public var teardown: [AutoTestStep]?
    /** Name of the autotest in autotest's card */
    public var title: String?
    /** Description of the autotest in autotest's card */
    public var description: String?
    /** Collection of the autotest labels */
    public var labels: [LabelApiModel]?
    /** Indicates if the autotest is marked as flaky */
    public var isFlaky: Bool?
    /** External key of the autotest */
    public var externalKey: String?
    /** Global ID of the autotest */
    public var globalId: Int64
    /** Unique ID of the autotest */
    public var id: UUID

    public init(externalId: String, links: [LinkApiResult]? = nil, projectId: UUID, name: String, namespace: String? = nil, classname: String? = nil, steps: [AutoTestStep]? = nil, setup: [AutoTestStep]? = nil, teardown: [AutoTestStep]? = nil, title: String? = nil, description: String? = nil, labels: [LabelApiModel]? = nil, isFlaky: Bool? = nil, externalKey: String? = nil, globalId: Int64, id: UUID) {
        self.externalId = externalId
        self.links = links
        self.projectId = projectId
        self.name = name
        self.namespace = namespace
        self.classname = classname
        self.steps = steps
        self.setup = setup
        self.teardown = teardown
        self.title = title
        self.description = description
        self.labels = labels
        self.isFlaky = isFlaky
        self.externalKey = externalKey
        self.globalId = globalId
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalId
        case links
        case projectId
        case name
        case namespace
        case classname
        case steps
        case setup
        case teardown
        case title
        case description
        case labels
        case isFlaky
        case externalKey
        case globalId
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(externalId, forKey: .externalId)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(namespace, forKey: .namespace)
        try container.encodeIfPresent(classname, forKey: .classname)
        try container.encodeIfPresent(steps, forKey: .steps)
        try container.encodeIfPresent(setup, forKey: .setup)
        try container.encodeIfPresent(teardown, forKey: .teardown)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(labels, forKey: .labels)
        try container.encodeIfPresent(isFlaky, forKey: .isFlaky)
        try container.encodeIfPresent(externalKey, forKey: .externalKey)
        try container.encode(globalId, forKey: .globalId)
        try container.encode(id, forKey: .id)
    }
}

