//
// AutoTestApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestApiResult: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var projectId: UUID
    public var externalId: String?
    public var name: String
    public var namespace: String?
    public var classname: String?
    public var steps: [AutoTestStepApiResult]?
    public var setup: [AutoTestStepApiResult]?
    public var teardown: [AutoTestStepApiResult]?
    public var title: String?
    public var description: String?
    public var isFlaky: Bool
    public var externalKey: String?
    public var globalId: Int64
    public var links: [LinkApiResult]?
    public var labels: [LabelApiResult]?
    public var tags: [String]?

    public init(id: UUID, projectId: UUID, externalId: String? = nil, name: String, namespace: String? = nil, classname: String? = nil, steps: [AutoTestStepApiResult]? = nil, setup: [AutoTestStepApiResult]? = nil, teardown: [AutoTestStepApiResult]? = nil, title: String? = nil, description: String? = nil, isFlaky: Bool, externalKey: String? = nil, globalId: Int64, links: [LinkApiResult]? = nil, labels: [LabelApiResult]? = nil, tags: [String]? = nil) {
        self.id = id
        self.projectId = projectId
        self.externalId = externalId
        self.name = name
        self.namespace = namespace
        self.classname = classname
        self.steps = steps
        self.setup = setup
        self.teardown = teardown
        self.title = title
        self.description = description
        self.isFlaky = isFlaky
        self.externalKey = externalKey
        self.globalId = globalId
        self.links = links
        self.labels = labels
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case projectId
        case externalId
        case name
        case namespace
        case classname
        case steps
        case setup
        case teardown
        case title
        case description
        case isFlaky
        case externalKey
        case globalId
        case links
        case labels
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(projectId, forKey: .projectId)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(namespace, forKey: .namespace)
        try container.encodeIfPresent(classname, forKey: .classname)
        try container.encodeIfPresent(steps, forKey: .steps)
        try container.encodeIfPresent(setup, forKey: .setup)
        try container.encodeIfPresent(teardown, forKey: .teardown)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(isFlaky, forKey: .isFlaky)
        try container.encodeIfPresent(externalKey, forKey: .externalKey)
        try container.encode(globalId, forKey: .globalId)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(labels, forKey: .labels)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

