//
// AutoTestFilterApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestFilterApiModel: Codable, JSONEncodable, Hashable {

    static let projectIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let externalIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let globalIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let nameRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    static let tagsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let excludeTagsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    /** Specifies an autotest projects IDs to search for */
    public var projectIds: Set<UUID>?
    /** Specifies an autotest external IDs to search for */
    public var externalIds: Set<String>?
    /** Specifies an autotest global IDs to search for */
    public var globalIds: Set<Int64>?
    /** Specifies an autotest name to search for */
    public var name: String?
    /** Specifies an autotest flaky status to search for */
    public var isFlaky: Bool?
    /** Specifies an autotest deleted status to search for */
    public var isDeleted: Bool?
    /** Specifies an autotest namespace to search for */
    public var namespace: String?
    /** Specifies an autotest class name to search for */
    public var className: String?
    /** Specifies an autotest external key to search for */
    public var externalKey: String?
    /** Specifies an autotest tags to search for */
    public var tags: Set<String>?
    /** Specifies an autotest tags to exclude */
    public var excludeTags: Set<String>?

    public init(projectIds: Set<UUID>? = nil, externalIds: Set<String>? = nil, globalIds: Set<Int64>? = nil, name: String? = nil, isFlaky: Bool? = nil, isDeleted: Bool? = nil, namespace: String? = nil, className: String? = nil, externalKey: String? = nil, tags: Set<String>? = nil, excludeTags: Set<String>? = nil) {
        self.projectIds = projectIds
        self.externalIds = externalIds
        self.globalIds = globalIds
        self.name = name
        self.isFlaky = isFlaky
        self.isDeleted = isDeleted
        self.namespace = namespace
        self.className = className
        self.externalKey = externalKey
        self.tags = tags
        self.excludeTags = excludeTags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectIds
        case externalIds
        case globalIds
        case name
        case isFlaky
        case isDeleted
        case namespace
        case className
        case externalKey
        case tags
        case excludeTags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(projectIds, forKey: .projectIds)
        try container.encodeIfPresent(externalIds, forKey: .externalIds)
        try container.encodeIfPresent(globalIds, forKey: .globalIds)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isFlaky, forKey: .isFlaky)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(namespace, forKey: .namespace)
        try container.encodeIfPresent(className, forKey: .className)
        try container.encodeIfPresent(externalKey, forKey: .externalKey)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(excludeTags, forKey: .excludeTags)
    }
}

