//
// CustomAttributeOptionUpdateApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomAttributeOptionUpdateApiModel: Codable, JSONEncodable, Hashable {

    static let valueRule = StringRule(minLength: 0, maxLength: 1024, pattern: nil)
    /** Unique ID of the attribute option */
    public var id: UUID
    /** Value of the attribute option */
    public var value: String?
    /** Indicates if the attribute option is used by default */
    public var isDefault: Bool
    /** Indicates if the attributes option is deleted */
    public var isDeleted: Bool

    public init(id: UUID, value: String? = nil, isDefault: Bool, isDeleted: Bool) {
        self.id = id
        self.value = value
        self.isDefault = isDefault
        self.isDeleted = isDeleted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case value
        case isDefault
        case isDeleted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encode(isDefault, forKey: .isDefault)
        try container.encode(isDeleted, forKey: .isDeleted)
    }
}

