//
// CustomAttributeSearchApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomAttributeSearchApiResult: Codable, JSONEncodable, Hashable {

    /** Projects where attribute is used in work items */
    public var workItemUsage: [ProjectShortestApiResult]
    /** Projects where attribute is used in test plans */
    public var testPlanUsage: [ProjectShortestApiResult]
    /** Unique ID of the attribute */
    public var id: UUID
    /** Optional code identifier for the attribute */
    public var code: String?
    /** Collection of the attribute options   Available for attributes of type `options` and `multiple options` only */
    public var options: [CustomAttributeOptionApiResult]
    /** Type of the attribute */
    public var type: CustomAttributeType
    /** Indicates if the attribute is deleted */
    public var isDeleted: Bool
    /** Name of the attribute */
    public var name: String
    /** Indicates if the attribute is enabled */
    public var isEnabled: Bool
    /** Indicates if the attribute value is mandatory to specify */
    public var isRequired: Bool
    /** Indicates if the attribute is available across all projects */
    public var isGlobal: Bool
    /** Indicates if the attribute is read-only */
    public var isReadOnly: Bool
    /** Indicates if the attribute is system */
    public var isSystem: Bool
    /** Collection of the attribute targets   Defines where the attribute can be used (e.g., TestCases, AutoTestCases, TestPlans) */
    public var targets: [String]

    public init(workItemUsage: [ProjectShortestApiResult], testPlanUsage: [ProjectShortestApiResult], id: UUID, code: String? = nil, options: [CustomAttributeOptionApiResult], type: CustomAttributeType, isDeleted: Bool, name: String, isEnabled: Bool, isRequired: Bool, isGlobal: Bool, isReadOnly: Bool, isSystem: Bool, targets: [String]) {
        self.workItemUsage = workItemUsage
        self.testPlanUsage = testPlanUsage
        self.id = id
        self.code = code
        self.options = options
        self.type = type
        self.isDeleted = isDeleted
        self.name = name
        self.isEnabled = isEnabled
        self.isRequired = isRequired
        self.isGlobal = isGlobal
        self.isReadOnly = isReadOnly
        self.isSystem = isSystem
        self.targets = targets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workItemUsage
        case testPlanUsage
        case id
        case code
        case options
        case type
        case isDeleted
        case name
        case isEnabled
        case isRequired
        case isGlobal
        case isReadOnly
        case isSystem
        case targets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workItemUsage, forKey: .workItemUsage)
        try container.encode(testPlanUsage, forKey: .testPlanUsage)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encode(options, forKey: .options)
        try container.encode(type, forKey: .type)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encode(name, forKey: .name)
        try container.encode(isEnabled, forKey: .isEnabled)
        try container.encode(isRequired, forKey: .isRequired)
        try container.encode(isGlobal, forKey: .isGlobal)
        try container.encode(isReadOnly, forKey: .isReadOnly)
        try container.encode(isSystem, forKey: .isSystem)
        try container.encode(targets, forKey: .targets)
    }
}

