//
// DetailedProjectApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DetailedProjectApiResult: Codable, JSONEncodable, Hashable {

    /** Collection of the project attributes */
    public var attributesScheme: [CustomAttributeApiResult]?
    /** ID of the workflow used in project */
    public var workflow: WorkflowApiResult
    /** Unique ID of the project */
    public var id: UUID
    /** Description of the project */
    public var description: String?
    /** Name of the project */
    public var name: String
    /** Indicates if the project is marked as favorite */
    public var isFavorite: Bool
    /** Indicates if the project is deleted */
    public var isDeleted: Bool
    /** Global ID of the project */
    public var globalId: Int64
    /** ID of the workflow used in project */
    public var workflowId: UUID

    public init(attributesScheme: [CustomAttributeApiResult]? = nil, workflow: WorkflowApiResult, id: UUID, description: String? = nil, name: String, isFavorite: Bool, isDeleted: Bool, globalId: Int64, workflowId: UUID) {
        self.attributesScheme = attributesScheme
        self.workflow = workflow
        self.id = id
        self.description = description
        self.name = name
        self.isFavorite = isFavorite
        self.isDeleted = isDeleted
        self.globalId = globalId
        self.workflowId = workflowId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributesScheme
        case workflow
        case id
        case description
        case name
        case isFavorite
        case isDeleted
        case globalId
        case workflowId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributesScheme, forKey: .attributesScheme)
        try container.encode(workflow, forKey: .workflow)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(name, forKey: .name)
        try container.encode(isFavorite, forKey: .isFavorite)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encode(globalId, forKey: .globalId)
        try container.encode(workflowId, forKey: .workflowId)
    }
}

