//
// ParameterApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ParameterApiResult: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var parameterKeyId: UUID
    public var name: String
    public var value: String
    public var isDeleted: Bool
    public var projectIds: [UUID]

    public init(id: UUID, parameterKeyId: UUID, name: String, value: String, isDeleted: Bool, projectIds: [UUID]) {
        self.id = id
        self.parameterKeyId = parameterKeyId
        self.name = name
        self.value = value
        self.isDeleted = isDeleted
        self.projectIds = projectIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case parameterKeyId
        case name
        case value
        case isDeleted
        case projectIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(parameterKeyId, forKey: .parameterKeyId)
        try container.encode(name, forKey: .name)
        try container.encode(value, forKey: .value)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encode(projectIds, forKey: .projectIds)
    }
}

