//
// ProjectApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProjectApiResult: Codable, JSONEncodable, Hashable {

    /** Unique ID of the project */
    public var id: UUID
    /** Description of the project */
    public var description: String?
    /** Name of the project */
    public var name: String
    /** Indicates if the project is marked as favorite */
    public var isFavorite: Bool
    /** Indicates if the project is deleted */
    public var isDeleted: Bool
    /** Global ID of the project */
    public var globalId: Int64
    /** ID of the workflow used in project */
    public var workflowId: UUID

    public init(id: UUID, description: String? = nil, name: String, isFavorite: Bool, isDeleted: Bool, globalId: Int64, workflowId: UUID) {
        self.id = id
        self.description = description
        self.name = name
        self.isFavorite = isFavorite
        self.isDeleted = isDeleted
        self.globalId = globalId
        self.workflowId = workflowId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case description
        case name
        case isFavorite
        case isDeleted
        case globalId
        case workflowId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(name, forKey: .name)
        try container.encode(isFavorite, forKey: .isFavorite)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encode(globalId, forKey: .globalId)
        try container.encode(workflowId, forKey: .workflowId)
    }
}

