//
// TestResultResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestResultResponse: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var stepComments: [StepCommentApiModel]?
    public var failureClassIds: [UUID]
    @available(*, deprecated, message: "This property is deprecated.")
    public var outcome: TestResultOutcome?
    public var status: TestStatusApiResult?
    public var comment: String?
    public var links: [LinkApiResult]?
    public var stepResults: [StepResultApiModel]?
    public var attachments: [AttachmentApiResult]?
    public var autoTestId: UUID?
    public var configurationId: UUID
    public var durationInMs: Int64?
    public var traces: String?
    public var failureType: String?
    public var message: String?
    public var testRunId: UUID
    public var autoTest: AutoTest?
    public var autoTestStepResults: [AutoTestStepResult]?
    public var setupResults: [AutoTestStepResult]?
    public var teardownResults: [AutoTestStepResult]?
    public var parameters: [String: String]?
    public var properties: [String: String]?

    public init(id: UUID, stepComments: [StepCommentApiModel]? = nil, failureClassIds: [UUID], outcome: TestResultOutcome? = nil, status: TestStatusApiResult? = nil, comment: String? = nil, links: [LinkApiResult]? = nil, stepResults: [StepResultApiModel]? = nil, attachments: [AttachmentApiResult]? = nil, autoTestId: UUID? = nil, configurationId: UUID, durationInMs: Int64? = nil, traces: String? = nil, failureType: String? = nil, message: String? = nil, testRunId: UUID, autoTest: AutoTest? = nil, autoTestStepResults: [AutoTestStepResult]? = nil, setupResults: [AutoTestStepResult]? = nil, teardownResults: [AutoTestStepResult]? = nil, parameters: [String: String]? = nil, properties: [String: String]? = nil) {
        self.id = id
        self.stepComments = stepComments
        self.failureClassIds = failureClassIds
        self.outcome = outcome
        self.status = status
        self.comment = comment
        self.links = links
        self.stepResults = stepResults
        self.attachments = attachments
        self.autoTestId = autoTestId
        self.configurationId = configurationId
        self.durationInMs = durationInMs
        self.traces = traces
        self.failureType = failureType
        self.message = message
        self.testRunId = testRunId
        self.autoTest = autoTest
        self.autoTestStepResults = autoTestStepResults
        self.setupResults = setupResults
        self.teardownResults = teardownResults
        self.parameters = parameters
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case stepComments
        case failureClassIds
        case outcome
        case status
        case comment
        case links
        case stepResults
        case attachments
        case autoTestId
        case configurationId
        case durationInMs
        case traces
        case failureType
        case message
        case testRunId
        case autoTest
        case autoTestStepResults
        case setupResults
        case teardownResults
        case parameters
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(stepComments, forKey: .stepComments)
        try container.encode(failureClassIds, forKey: .failureClassIds)
        try container.encodeIfPresent(outcome, forKey: .outcome)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(stepResults, forKey: .stepResults)
        try container.encodeIfPresent(attachments, forKey: .attachments)
        try container.encodeIfPresent(autoTestId, forKey: .autoTestId)
        try container.encode(configurationId, forKey: .configurationId)
        try container.encodeIfPresent(durationInMs, forKey: .durationInMs)
        try container.encodeIfPresent(traces, forKey: .traces)
        try container.encodeIfPresent(failureType, forKey: .failureType)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encode(testRunId, forKey: .testRunId)
        try container.encodeIfPresent(autoTest, forKey: .autoTest)
        try container.encodeIfPresent(autoTestStepResults, forKey: .autoTestStepResults)
        try container.encodeIfPresent(setupResults, forKey: .setupResults)
        try container.encodeIfPresent(teardownResults, forKey: .teardownResults)
        try container.encodeIfPresent(parameters, forKey: .parameters)
        try container.encodeIfPresent(properties, forKey: .properties)
    }
}

