//
// TestStatusApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestStatusApiResult: Codable, JSONEncodable, Hashable {

    public var id: UUID
    /** Collection of possible status types */
    public var type: TestStatusApiType
    public var code: String

    public init(id: UUID, type: TestStatusApiType, code: String) {
        self.id = id
        self.type = type
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case type
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(type, forKey: .type)
        try container.encode(code, forKey: .code)
    }
}

