//
// TestRunApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestRunApiResult: Codable, JSONEncodable, Hashable {

    /** Test run unique identifier */
    public var id: UUID
    /** Test run name */
    public var name: String
    /** Test run state */
    @available(*, deprecated, message: "This property is deprecated.")
    public var stateName: TestRunState
    /** Test run status */
    public var status: TestStatusApiResult
    /** Collection of attachments related to the test run */
    public var attachments: [AttachmentApiResult]
    /** Collection of links related to the test run */
    public var links: [LinkApiResult]
    /** Collection of tags associated with the test run */
    public var tags: [String]
    /** Test run description (needed for round-trip update; adapters GET omits it on TMS 5.8) */
    public var description: String?
    /** Test run launch source (needed for round-trip update; adapters GET omits it on TMS 5.8) */
    public var launchSource: String?

    public init(
        id: UUID,
        name: String,
        stateName: TestRunState,
        status: TestStatusApiResult,
        attachments: [AttachmentApiResult],
        links: [LinkApiResult],
        tags: [String],
        description: String? = nil,
        launchSource: String? = nil
    ) {
        self.id = id
        self.name = name
        self.stateName = stateName
        self.status = status
        self.attachments = attachments
        self.links = links
        self.tags = tags
        self.description = description
        self.launchSource = launchSource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case stateName
        case status
        case attachments
        case links
        case tags
        case description
        case launchSource
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(stateName, forKey: .stateName)
        try container.encode(status, forKey: .status)
        try container.encode(attachments, forKey: .attachments)
        try container.encode(links, forKey: .links)
        try container.encode(tags, forKey: .tags)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(launchSource, forKey: .launchSource)
    }
}
