//
// TestResultShortResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestResultShortResponse: Codable, JSONEncodable, Hashable {

    /** Unique ID of the test result */
    public var id: UUID
    /** Name of autotest represented by the test result */
    public var name: String
    /** External ID of autotest represented by the test result */
    public var autotestExternalId: String?
    /** Tags of the autotest represented by the test result */
    public var autoTestTags: [String]
    /** Unique ID of test run where the test result is located */
    public var testRunId: UUID
    /** Unique ID of configuration which the test result uses */
    public var configurationId: UUID
    /** Name of configuration which the test result uses */
    public var configurationName: String
    /** Outcome of the test result */
    @available(*, deprecated, message: "This property is deprecated.")
    public var outcome: String?
    public var status: TestStatusApiResult
    /** Collection of result reasons which the test result have */
    public var resultReasons: [AutoTestResultReasonShort]
    /** Comment to the test result */
    public var comment: String?
    /** Time which it took to run the test */
    public var duration: Int64?
    /** Collection of links attached to the test result */
    public var links: [TestResultLinkApiResult]
    /** Collection of files attached to the test result */
    public var attachments: [AttachmentApiResult]
    /** Run count */
    public var rerunCompletedCount: Int

    public init(id: UUID, name: String, autotestExternalId: String? = nil, autoTestTags: [String], testRunId: UUID, configurationId: UUID, configurationName: String, outcome: String? = nil, status: TestStatusApiResult, resultReasons: [AutoTestResultReasonShort], comment: String? = nil, duration: Int64? = nil, links: [TestResultLinkApiResult], attachments: [AttachmentApiResult], rerunCompletedCount: Int) {
        self.id = id
        self.name = name
        self.autotestExternalId = autotestExternalId
        self.autoTestTags = autoTestTags
        self.testRunId = testRunId
        self.configurationId = configurationId
        self.configurationName = configurationName
        self.outcome = outcome
        self.status = status
        self.resultReasons = resultReasons
        self.comment = comment
        self.duration = duration
        self.links = links
        self.attachments = attachments
        self.rerunCompletedCount = rerunCompletedCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case autotestExternalId
        case autoTestTags
        case testRunId
        case configurationId
        case configurationName
        case outcome
        case status
        case resultReasons
        case comment
        case duration
        case links
        case attachments
        case rerunCompletedCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(autotestExternalId, forKey: .autotestExternalId)
        try container.encode(autoTestTags, forKey: .autoTestTags)
        try container.encode(testRunId, forKey: .testRunId)
        try container.encode(configurationId, forKey: .configurationId)
        try container.encode(configurationName, forKey: .configurationName)
        try container.encodeIfPresent(outcome, forKey: .outcome)
        try container.encode(status, forKey: .status)
        try container.encode(resultReasons, forKey: .resultReasons)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encode(links, forKey: .links)
        try container.encode(attachments, forKey: .attachments)
        try container.encode(rerunCompletedCount, forKey: .rerunCompletedCount)
    }
}

