//
// WorkItemShortApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemShortApiResult: Codable, JSONEncodable, Hashable {

    /** Work Item internal unique identifier */
    public var id: UUID
    /** Work Item name */
    public var name: String
    /** Work Item type. Possible values: CheckLists, SharedSteps, TestCases */
    public var entityTypeName: String
    /** Project unique identifier */
    public var projectId: UUID
    /** Identifier of Section where Work Item is located */
    public var sectionId: UUID
    /** Section name of Work Item */
    public var sectionName: String
    /** Boolean flag determining whether Work Item is automated */
    public var isAutomated: Bool
    /** Work Item global identifier */
    public var globalId: Int64
    /** Work Item duration */
    public var duration: Int64
    /** Work Item attributes */
    public var attributes: [String: AnyCodable]?
    /** The current state of Work Item */
    public var state: WorkItemStates
    /** Work Item priority level */
    public var priority: WorkItemPriorityModel
    /** Work Item priority level */
    public var sourceType: WorkItemSourceTypeModel
    /** Flag determining whether Work Item is deleted */
    public var isDeleted: Bool
    /** Array of tag names of Work Item */
    public var tagNames: [String]?
    /** Set of iterations related to Work Item */
    public var iterations: [IterationApiResult]
    /** Set of links related to Work Item */
    public var links: [LinkShortApiResult]

    public init(id: UUID, name: String, entityTypeName: String, projectId: UUID, sectionId: UUID, sectionName: String, isAutomated: Bool, globalId: Int64, duration: Int64, attributes: [String: AnyCodable]? = nil, state: WorkItemStates, priority: WorkItemPriorityModel, sourceType: WorkItemSourceTypeModel, isDeleted: Bool, tagNames: [String]? = nil, iterations: [IterationApiResult], links: [LinkShortApiResult]) {
        self.id = id
        self.name = name
        self.entityTypeName = entityTypeName
        self.projectId = projectId
        self.sectionId = sectionId
        self.sectionName = sectionName
        self.isAutomated = isAutomated
        self.globalId = globalId
        self.duration = duration
        self.attributes = attributes
        self.state = state
        self.priority = priority
        self.sourceType = sourceType
        self.isDeleted = isDeleted
        self.tagNames = tagNames
        self.iterations = iterations
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case entityTypeName
        case projectId
        case sectionId
        case sectionName
        case isAutomated
        case globalId
        case duration
        case attributes
        case state
        case priority
        case sourceType
        case isDeleted
        case tagNames
        case iterations
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(entityTypeName, forKey: .entityTypeName)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(sectionId, forKey: .sectionId)
        try container.encode(sectionName, forKey: .sectionName)
        try container.encode(isAutomated, forKey: .isAutomated)
        try container.encode(globalId, forKey: .globalId)
        try container.encode(duration, forKey: .duration)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encode(state, forKey: .state)
        try container.encode(priority, forKey: .priority)
        try container.encode(sourceType, forKey: .sourceType)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(tagNames, forKey: .tagNames)
        try container.encode(iterations, forKey: .iterations)
        try container.encode(links, forKey: .links)
    }
}

