//
// WorkItemSelectApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemSelectApiModel: Codable, JSONEncodable, Hashable {

    public var filter: WorkItemFilterApiModel

    public init(filter: WorkItemFilterApiModel) {
        self.filter = filter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filter, forKey: .filter)
    }
}

