//
// WorkflowApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkflowApiResult: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var statuses: [WorkflowStatusApiResult]

    public init(id: UUID, statuses: [WorkflowStatusApiResult]) {
        self.id = id
        self.statuses = statuses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case statuses
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(statuses, forKey: .statuses)
    }
}

