//
// WorkflowStatusApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkflowStatusApiResult: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var code: String
    /** Collection of possible status types */
    public var type: TestStatusApiType

    public init(id: UUID, code: String, type: TestStatusApiType) {
        self.id = id
        self.code = code
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case code
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(code, forKey: .code)
        try container.encode(type, forKey: .type)
    }
}

